#!/bin/bash
today=`date +%Y-%m-%d.%H:%M:%S`
git add -A && git commit -m "push_$today $1" && git push && ssh -i ~/.ssh/bd-ssh pennyapple@35.221.129.234 sudo ./up_fish_all && ssh -i ~/.ssh/bd-ssh pennyapple@34.80.8.20 sudo ./up_fish
